#!/bin/bash
function continuo {
	msgm="$1"
	[ -z "$1" ] &&	msgm="Continuar"
	SIG ">";echo -en "\e[1;32m""$msgm"" \e[0m[y/n/pular][Padrao: y]? "
	read -t5 -n1 opsao
	[[ "$opsao" = "n" || "$opsao" = "N" ]] &&	exit 1
	[[ "$opsao" = "p" || "$opsao" = "P" ]] &&	return 1
	return 0
}
function SIG {
	case $1 in
		"+") echo -en "\n\e[1;34m [\e[0m\e[1;32;1m+\e[0m\e[1;34m] $2\e[0m" ;;
		"-") echo -en "\n\e[1;34m [\e[0m\e[1;31;1m-\e[0m\e[1;34m] $2\e[0m" ;;
		">") echo -en "\n\e[1;34m [\e[0m\e[1;37;1m>\e[0m\e[1;34m] $2\e[0m" ;;
		".") echo -en "\n\e[1;34m [\e[0m\e[1;35;1m.\e[0m\e[1;34m] $2\e[0m" ;;
		"err") SIG "-"; echo -en "\e[5;31mERRO $2\e[0m" ;;
		"ok")  SIG "+"; ;;
		*)	   echo -en "\e[1;34m [\e[0m\e[1;37;1m$1\e[0m\e[1;34m] $2\e[0m"
	esac
}
function pre_teste { #[comando]
	if ! ( which "$1");then
		SIG err "ERRO" "$1" "Não esta instalado!"
		exit 1
	fi
}
function exit_erro {
	SIG "err"
	echo -en "$1"
	exit 1
}

function instalar {
	SIG ".";echo -en "\e[1;0;1mInstalando\e[0m \e[1;32m$1\e[0m:\n"

	comando="( SIG 'err' 'Arquivo nao Valido' && exit 1 )"
	[[ "$2" = "rpm" || "$2" = "RPM" ]] && pre_teste "rpm"
	[[ "$2" = "deb" || "$2" = "DEB" ]] && pre_teste "dpkg"
	[[ "$2" = "rpm" || "$2" = "RPM" ]] && comando="( sudo rpm -i --nodigest $1 )"
	[[ "$2" = "deb" || "$2" = "DEB" ]] && comando="( sudo dpkg -i $1 )"
	if continuo ;then
		if ! $(eval $comando) ;then
			exit_erro "de instalaçao!\n"
		else
			SIG "+" "Instalado com Sucesso!";	fi
	fi
    SIG ".";echo -en "Configurando >>\n"
	if continuo ;then
		if ! sudo /opt/sentinelone/bin/sentinelctl management token set $token;then
			exit_erro "de token\n"
		else
			SIG "+" "Token Instalado";	fi
	fi
	if continuo ;then
		if ! sudo /opt/sentinelone/bin/sentinelctl control start ; then
			exit_erro "on start SentinelOne\n"
		else
			SIG "+" "SentinelOne Started";	fi
	fi
	SIG ">" "Waiting ." ; sleep 2 ; echo -en " ." ; sleep 2 ; echo -en " ." ; sleep 2

	SIG "+" "Agente Status:"
	if ! sudo /opt/sentinelone/bin/sentinelctl control status ;then
                SIG "err";echo -en "on start SentinelOne\n";fi
}
function lista(){
#
	if ! ( sudo ls $1/ > '/dev/null' );then
		exit_erro "no diretorio \e[1;37m$1\e[0m"
		exit
	fi
	SIG ".";echo -en "Escolha o arquivo a ser instalado: \n"

	for ARQ in $( ls $1/ )
	do
	i="$1/$ARQ"
		if [ -f $i ];then
			last=$((${#i}-4))
			if [ "${i:$last:4}" = ".deb" ] || [ "${i:$last:4}" = ".DEB" ] || [ "${i:$last:4}" = ".rpm" ] || [ "${i:$last:4}" = ".RPM" ];then
				nArq=$(($nArq+1))
				lista_repositorio+=($ARQ)
				echo -en "\n\t";SIG "$nArq" "${i:$last:4}"; echo -en ":  ${lista_repositorio[$nArq]}"
			fi
		fi
	done
	echo -en "\n"
}
nArq=0
lista_repositorio=( "$nArq" )
if [ -r token.txt ]
then
    token=$(cat token.txt)
    SIG ">" "Group Token:";
    SIG "." ; echo -en "\e[1;37;$token\e[0m"
    lista "."
	SIG ">" ; read -n1 arq_install
	nome_arq_install="${lista_repositorio[$arq_install]}"
	SIG ">" "$nome_arq_install";
	if [ -a  "$nome_arq_install" ];then
		last=$((${#lista_repositorio[$arq_install]}-3))
		tipo="${lista_repositorio[$arq_install]:$last:3}"
		instalar "$nome_arq_install" "$tipo"
	else
		exit_erro "Arquivo Nao Existe"
	fi
	if continuo "Criar Script facilitador [OneSentinel]?"; then
		echo -en "\n"
		SIG "$.PATH" "/n$PATH"
		SIG ">" "Diretório: " ; read usrGames
		[[ "$usrGames" = "" ]] && usrGames="/usr/games"
		if ! sudo touch "$usrGames/OneSentinel";then
			exit_erro "na criação de $usrGames/OneSentinel"
		else
			echo -e "#!/bin/bash\necho -e 'SentinelOne agent commandline control
Usage: /opt/sentinelone/bin/sentinelctl [OPTIONS] SUBCOMMAND'
sudo /opt/sentinelone/bin/sentinelctl $""1" | sudo tee -a "$usrGames/OneSentinel"
			SIG "+" "Adicionado $usrGames/OneSentinel \n"
		fi

	fi

else
  exit_erro "NO token\n"
fi
